### ISSUE TITLE
Provide file hash code.

### ISSUE THREAD

**Issue by newpro** [epic-kitchens/download-scripts#1]
Hey epic team.

Thanks very much for providing the dataset! It is an exciting time to be alive, having egocentric dataset at this magnitude level. 

The file download takes a long time, therefore requires constant good connection during the time. In my experience of downloading the script, it is observed that most likely due to Internet connection, some files are broken, and others did not download. The following lines represent two situations from download logs:

* Broken file:
```
-ne # Downloading frames_rgb_flow/rgb/test/P18/P18_10.tar	
 45%-ne 
 # done
```

* Fail to download:
```
-ne # Downloading frames_rgb_flow/rgb/test/P18/P18_11.tar	
-ne 
 # done
```

Currently, it is required to check download logs line by line to re-download brokens. If the team can present a script to check file integrities by hash code and generates broken file list it would be great. If it is too much trouble, present a list of file, with their hash code in a txt file would also work. Thanks in advance!

Cheers!

**Comment by davidemoltisanti** [comment]
Hi @newpro , thank you very much for your positive feedback!

I have just updated the scripts so that any incomplete file will be resumed, in order to allow downloading big files in multiple goes. 

Provided that the script completes, there should be no broken files.

Hope this helps! Please let me know if there any issues.

Thanks
